### ISSUE TITLE
Integrate with `vector_math`

### ISSUE THREAD

**Issue by hermanbergwerf** [rhulha/ChronosGL#23]
There is a pretty cool pub package for vector and matrix operations; `vector_math` (http://pub.dartlang.org/packages/vector_math). It would be awesome if you could integrate with this package so I can use the same types (e.g. it also has a `Vector3List` with a single `Float32List` backend).

**Comment by muth02446** [comment]
Hi Herman (and Raymond):

I am working on this but since it is a rather big change breaking compatibility with older code
in rather dramatic way I was thinking of combining this with a WebGL 2.0 port.

Cheers,
Robert

**Comment by rhulha** [comment]
Yeah, I think it makes sense to switch to vector_math too.

**Comment by unicomp21** [comment]
awesome!

**Comment by muth02446** [comment]
I went ahead and did this in branch:
https://github.com/rhulha/ChronosGL/tree/NewShaderLogic

Note that this branch contains many incompatible API changes 
*beyond* the vector_math changes.
I am also still exploring stuff like "phases" and do not consider the API fully stable.
In case of doubt have a look at the examples.

Not that this does not include anything related to WebGL 2.0.
Dartium is still at Chrome 45 equivalent so it might be while before we can 
experiment with WebGL 2.0 and Dart.

@rhulha 
I put a few "TODO(rhulha)" in places where I did not quite knew what to do.

**Comment by rhulha** [comment]
I'll try to take a look but I am strapped for time :/

**Comment by muth02446** [comment]
I consider this done now.
In addition to the vector_math changes there has been a lot of "churn" in the API.
I am happy with the new abstractions, so they should be quite stable now.

Please have a  look at the high level overview here: https://github.com/rhulha/ChronosGL/blob/NewShaderLogic/class_glossary.md
and check the examples to see how things work in detail.
